"""
backend.orchestration.state_manager

Defines the canonical LangGraph state schema (WorkflowState) for the agent workflow engine.

Design philosophy — state holds references only:
    - Heavy data (extracted text, transformed payloads, integration responses) is stored
      in Supabase by each agent immediately after it is produced.
    - Agents write only the resulting Supabase row IDs back into state.
    - This keeps the state object small and cheap, making LangGraph checkpointing fast.

Checkpointing:
    LangGraph's AsyncPostgresSaver (backed by Supabase PostgreSQL) intercepts every
    state transition automatically. No manual serialisation is needed — because state
    only ever carries primitives (str, list[str], list[dict]), it round-trips through
    JSON without loss.

Reducer pattern:
    All accumulator fields (lists that grow as agents complete work) are annotated with
    `operator.add` as their reducer. This tells LangGraph how to merge concurrent writes
    from parallel agent branches — new IDs are appended rather than overwritten.
"""

import operator
from typing import Annotated, TypedDict


# ---------------------------------------------------------------------------
# State schema
# ---------------------------------------------------------------------------

class WorkflowState(TypedDict):
    """
    The single source of truth threaded through every node in the LangGraph graph.

    All fields are intentionally lightweight:
        - Scalar strings for identity and control flow.
        - Plain dicts for task metadata (status, agent_type, id — NOT full payloads).
        - Lists of string IDs pointing at rows in Supabase for every heavy artifact.

    Accumulator lists (anything that agents append to rather than replace) are typed
    with `Annotated[list[...], operator.add]` so that LangGraph's state merge logic
    concatenates parallel writes instead of clobbering them.
    """

    # ------------------------------------------------------------------
    # Core identity & control
    # ------------------------------------------------------------------

    workflow_id: str
    """UUID string of the parent WorkflowRequest — used to namespace Supabase writes."""

    status: str
    """
    Current lifecycle phase of the workflow. Typical progression:
        initializing → running → completed | failed | partial
    Agents may also write domain-specific statuses (e.g. 'extracting', 'transforming').
    """

    user_request: str
    """The raw instruction string submitted by the user that triggered this workflow."""

    # ------------------------------------------------------------------
    # Task routing metadata
    # ------------------------------------------------------------------

    tasks: Annotated[list[dict], operator.add]
    """
    Lightweight task descriptors generated by the router agent. Each dict holds:
        {
            "id":         str,   # UUID for this task
            "agent_type": str,   # e.g. "researcher", "summarizer"
            "description": str,  # short intent summary only
            "status":     str,   # pending | in_progress | completed | failed
        }
    Full task payloads (inputs, raw outputs) are never stored here — they live in Supabase.
    """

    # ------------------------------------------------------------------
    # Task outcome tracking (accumulate as agents finish)
    # ------------------------------------------------------------------

    completed_task_ids: Annotated[list[str], operator.add]
    """UUIDs of tasks that have finished successfully. Appended by each agent on success."""

    failed_task_ids: Annotated[list[str], operator.add]
    """UUIDs of tasks that raised an unrecoverable error. Appended by each agent on failure."""

    # ------------------------------------------------------------------
    # Supabase row ID references — heavy data lives there, not here
    # ------------------------------------------------------------------

    extracted_data_ids: Annotated[list[str], operator.add]
    """
    Supabase row IDs for raw extracted artifacts (web content, document text, etc.)
    written by researcher / extractor agents.
    """

    transformed_data_ids: Annotated[list[str], operator.add]
    """
    Supabase row IDs for cleaned, structured records produced by transformer agents.
    """

    integration_result_ids: Annotated[list[str], operator.add]
    """
    Supabase row IDs for payloads sent to or received from external integrations
    (APIs, CRMs, databases), written by executor agents.
    """

    notification_result_ids: Annotated[list[str], operator.add]
    """
    Supabase row IDs for outgoing notification records (emails, Slack messages, webhooks)
    dispatched during the workflow run.
    """

    error_ids: Annotated[list[str], operator.add]
    """
    Supabase row IDs for ExecutionError rows persisted by the error handler node.
    Kept separate from `failed_task_ids` so errors can be fetched and displayed in
    detail without re-querying across the full task table.
    """

    # ------------------------------------------------------------------
    # Terminal output
    # ------------------------------------------------------------------

    final_summary: str
    """
    Human-readable summary synthesised by the summarizer agent at the end of the run.
    Written once; subsequent nodes should treat this as read-only.
    """


# ---------------------------------------------------------------------------
# Factory helper
# ---------------------------------------------------------------------------

def get_initial_state(workflow_id: str, user_request: str) -> WorkflowState:
    """
    Build and return a clean WorkflowState for the start of a new workflow run.

    All accumulator lists are initialised to empty so that LangGraph's `operator.add`
    reducer can safely append to them from any node without encountering None.

    Args:
        workflow_id:  UUID string assigned by the API layer to this workflow run.
        user_request: The raw user instruction that triggered the workflow.

    Returns:
        A fully-populated WorkflowState with status="initializing" and no prior data.
    """
    return WorkflowState(
        workflow_id=workflow_id,
        status="initializing",
        user_request=user_request,
        # Task routing
        tasks=[],
        # Outcome tracking
        completed_task_ids=[],
        failed_task_ids=[],
        # Supabase reference IDs — populated by agents as they run
        extracted_data_ids=[],
        transformed_data_ids=[],
        integration_result_ids=[],
        notification_result_ids=[],
        error_ids=[],
        # Terminal output — empty until the summarizer agent writes it
        final_summary="",
    )
